baseURL = 'https://theblek.online'
languageCode = 'en-us'
title = 'theblek'
theme = 'hugo-theme-m10c'

[params]
	author = 'Kuklin Georgiy'
	description = 'Software engineer interested in the nitty-gritty of computing'
	avatar = 'myavatar.jpg'
	[[params.social]]
		icon = "brand-github"
		name = "Github"
		url = "https://github.com/TheBlek"
	[[params.social]]
		icon = "brand-telegram"
		name = "Telegram"
		url = "https://t.me/theblek_games"
	[[params.social]]
		icon = "mail"
		name = "Email"
		url = "mailto:theblekbern@gmail.com"
	
